providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    network: traefik
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  webinsecure:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web
          scheme: https
  web:
    address: ":443"
    http:
      tls: true

certificatesResolvers:
  cloudflare:
    acme:
      email: me@example.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

api:
  dashboard: true
  debug: true
