providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entryPoints:
  webinsecure:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web
          scheme: https
  web:
    address: ":443"
    http:
      tls: true

api:
  dashboard: true
  debug: false
